[package]
name = "simple-http-server"
version = "0.2.2"
authors = ["T0mstone <realt0mstone@gmail.com>"]
edition = "2021"

[dependencies]
rouille = "3"
toml = "0.8"
serde_derive = "1.0.193"
serde = "1.0.193"
mime = "0.3"
