[package]
name = "simple-http-server"
version = "0.1.0"
authors = ["T0mstone <realt0mstone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0.0"
structopt = "0.3.20"
toml = "0.5.7"
serde_derive = "1.0.117"
serde = "1.0.117"
thiserror = "1.0.22"
mime = "0.3.16"