# The config file
# For the format, see README.md

addr = "localhost:8000"
failsafe_addrs = ["localhost:8001"]
index = "index.html"

[get_routes]
direct = ["index.html"]
"style.css" = "style.css"
"favicon.ico" = { type = "image/png", path = "favicon.png" }