# The config file
# For the format, see README.md

index = "index.html"
addr = "localhost:8000"
failsafe_addrs = ["localhost:8001"]
host_files = ["index.html"]

[get_routes]
"style.css" = "style.css"
"favicon.ico" = { type = "image/png", path = "favicon.png" }